# Generated by Django 6.0.4 on 2026-04-09 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('uzmanlik_alani', models.CharField(max_length=120, verbose_name='Uzmanlik Alani')),
                ('eposta', models.EmailField(max_length=254, unique=True, verbose_name='E-Posta')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi')),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktorlar',
                'ordering': ['ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='Hasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('tc_kimlik_no', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('dogum_tarihi', models.DateField(verbose_name='Dogum Tarihi')),
                ('cinsiyet', models.CharField(max_length=10, verbose_name='Cinsiyet')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randevu_tarihi', models.DateTimeField(verbose_name='Randevu Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('durum', models.CharField(choices=[('planlandi', 'Planlandi'), ('iptal', 'Iptal'), ('tamamlandi', 'Tamamlandi')], default='planlandi', max_length=20, verbose_name='Durum')),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='klinik.doktor', verbose_name='Doktor')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevular', to='klinik.hasta', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['-randevu_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='TibbiKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yas', models.PositiveIntegerField(verbose_name='Yas')),
                ('anemi', models.BooleanField(verbose_name='Anemi')),
                ('kreatinin_fosfokinaz', models.FloatField(verbose_name='Kreatinin Fosfokinaz')),
                ('diyabet', models.BooleanField(verbose_name='Diyabet')),
                ('ejeksiyon_fraksiyonu', models.FloatField(verbose_name='Ejeksiyon Fraksiyonu')),
                ('yuksek_tansiyon', models.BooleanField(verbose_name='Yuksek Tansiyon')),
                ('trombosit', models.FloatField(verbose_name='Trombosit')),
                ('serum_kreatinin', models.FloatField(verbose_name='Serum Kreatinin')),
                ('serum_sodyum', models.FloatField(verbose_name='Serum Sodyum')),
                ('cinsiyet_erkek', models.BooleanField(verbose_name='Cinsiyet Erkek')),
                ('sigara', models.BooleanField(verbose_name='Sigara')),
                ('takip_suresi', models.PositiveIntegerField(verbose_name='Takip Suresi')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayit Tarihi')),
                ('hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tibbi_kayitlar', to='klinik.hasta', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Tibbi Kayit',
                'verbose_name_plural': 'Tibbi Kayitlar',
                'ordering': ['-kayit_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='TahminSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karar_agaci_tahmini', models.BooleanField(verbose_name='Karar Agaci Tahmini')),
                ('knn_tahmini', models.BooleanField(verbose_name='KNN Tahmini')),
                ('naive_bayes_tahmini', models.BooleanField(verbose_name='Naive Bayes Tahmini')),
                ('rastgele_orman_tahmini', models.BooleanField(verbose_name='Rastgele Orman Tahmini')),
                ('lojistik_regresyon_tahmini', models.BooleanField(verbose_name='Lojistik Regresyon Tahmini')),
                ('toplu_tahmin', models.BooleanField(verbose_name='Toplu Tahmin')),
                ('olasilik', models.FloatField(default=0.0, verbose_name='Olasilik')),
                ('tahmin_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Tahmin Tarihi')),
                ('tibbi_kayit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tahmin_sonuclari', to='klinik.tibbikayit', verbose_name='Tibbi Kayit')),
            ],
            options={
                'verbose_name': 'Tahmin Sonucu',
                'verbose_name_plural': 'Tahmin Sonuclari',
                'ordering': ['-tahmin_tarihi'],
            },
        ),
    ]
